name: Process Axon PGN

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install chess

      - name: Run filter (only PGN)
        run: python convert.py

      - name: Install polyglot
        run: |
          sudo apt-get update
          sudo apt-get install polyglot -y

      - name: Convert PGN → BIN
        run: polyglot make-book -pgn axon.pgn -bin axon.bin -min-game 1 -max-ply 200

      - name: Upload filtered PGN
        uses: actions/upload-artifact@v4
        with:
          name: axon-pgn
          path: axon.pgn

      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: axon-bin
          path: axon.bin
