name: Sync Syzygy (no LFS) from Mypant → Myshirt

on:
  workflow_dispatch: # Manual run
  # schedule:
  #   - cron: "0 2 * * *"  # Runs daily at 02:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Myshirt (private repo)
        run: |
          echo "Cloning Myshirt..."
          git clone https://x-access-token:${{ secrets.EXO }}@github.com/zonalraid45/Myshirt.git Myshirt
          cd Myshirt
          # Make sure we disable LFS completely
          git lfs uninstall || true
          # Remove any old tracking rule
          sed -i '/syzygy/d' .gitattributes || true

      - name: Clone Mypant repo
        run: |
          echo "Cloning Mypant..."
          git clone https://github.com/zonalraid45/Mypant.git Mypant
          ls -la Mypant/engines/syzygy

      - name: Copy syzygy into Myshirt root
        run: |
          echo "Copying syzygy folder into Myshirt..."
          rm -rf Myshirt/syzygy || true
          cp -r Mypant/engines/syzygy Myshirt/syzygy
          ls -la Myshirt/syzygy

      - name: Commit & Push syzygy (normal Git files)
        run: |
          cd Myshirt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Make sure syzygy is not tracked with LFS
          git lfs untrack "syzygy/**" || true
          git add .gitattributes || true

          git add syzygy
          git commit -m "Add/Update syzygy folder from Mypant (normal Git files)" || echo "No changes to commit"
          git push origin main
