name: Sync Syzygy (LFS) from Mypant → Myshirt

on:
  workflow_dispatch: # Manual run
  # schedule:
  #   - cron: "0 2 * * *"  # Runs daily at 02:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git LFS
        run: |
          echo "Installing Git LFS..."
          sudo apt-get update
          sudo apt-get install git-lfs -y
          git lfs install

      - name: Clone Myshirt (private repo)
        run: |
          echo "Cloning Myshirt..."
          git clone https://x-access-token:${{ secrets.EXO }}@github.com/zonalraid45/Myshirt.git Myshirt
          cd Myshirt
          git lfs install

      - name: Clone Mypant repo
        run: |
          echo "Cloning Mypant..."
          git clone https://github.com/zonalraid45/Mypant.git Mypant
          ls -la Mypant/engines/syzygy

      - name: Copy syzygy into Myshirt root
        run: |
          echo "Copying syzygy folder into Myshirt..."
          rm -rf Myshirt/syzygy || true
          cp -r Mypant/engines/syzygy Myshirt/syzygy
          ls -la Myshirt/syzygy

      - name: Commit & Push syzygy (via Git LFS)
        run: |
          cd Myshirt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git lfs track "syzygy/**"
          git add .gitattributes
          git add syzygy

          git commit -m "Add/Update syzygy folder from Mypant (LFS)" || echo "No changes to commit"
          git push origin main
