name: Sync Anti-syzygy (download from files.txt) → Myshirt

on:
  workflow_dispatch: # Manual run
  # schedule:
  #   - cron: "0 2 * * *"  # Runs daily at 02:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workflow repo (to access files.txt)
        uses: actions/checkout@v4

      - name: Clone Myshirt (private repo)
        run: |
          echo "Cloning Myshirt..."
          git clone https://x-access-token:${{ secrets.EXO }}@github.com/zonalraid45/Myshirt.git Myshirt
          cd Myshirt
          # Disable LFS to avoid large file tracking
          git lfs uninstall || true
          # Remove any old tracking rule
          sed -i '/Anti-syzygy/d' .gitattributes || true

      - name: Download Anti-syzygy files from files.txt
        run: |
          echo "Downloading Anti-syzygy files..."
          mkdir -p Anti-syzygy
          cd Anti-syzygy

          # Use files.txt from Workflow repo root
          xargs -n 1 wget -c -N < ../files.txt

          echo "Downloaded files:"
          ls -lh
          cd ..

      - name: Move Anti-syzygy into Myshirt
        run: |
          echo "Placing Anti-syzygy into Myshirt..."
          rm -rf Myshirt/Anti-syzygy || true
          mv Anti-syzygy Myshirt/Anti-syzygy
          ls -lh Myshirt/Anti-syzygy | head -n 20

      - name: Commit & Push Anti-syzygy
        run: |
          cd Myshirt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git lfs untrack "Anti-syzygy/**" || true
          git add .gitattributes || true

          git add Anti-syzygy
          git commit -m "Update Anti-syzygy tablebase from files.txt" || echo "No changes to commit"
          git push origin main
